version: '3.7'

services: 

  web_nginx:
    build:
      context: ../
      dockerfile: nginx.Dockerfile
    container_name: blog_web_nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - webDir:/www/web
    

  web:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: blog_web
    volumes:
      - webDir:/www/web

volumes: 
  webDir: