version: '3.7'

services: 

  web_nginx:
    build:
      context: ../
      dockerfile: nginx.Dockerfile
    container_name: blog_web_nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - webDist:/webDist
    

  web:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: blog_web
    volumes:
      - webDist:/www/web/build

volumes: 
  webDist: